**What is Numpy?**
+ Numpy is python package used for Scientific Computing.
+  It add support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

In [0]:
#Creating a Numpy array

import numpy as np #Import the Library

x = np.array([1,2,3]) 

print(x) #This will print single dimensional array

[1 2 3]


In [0]:
y = np.array([(1,2,3),(4,5,6)])

print(y) #This will print 2-D array

[[1 2 3]
 [4 5 6]]


**Why to use Numpy when i have List?**
+ Faster
+ Consume Less Memory
+ More Convenient

In [0]:
import numpy as np

import time

import sys  

In [0]:
#Fast

size = 1000000

#List
L1 = range(size)
L2 = range(size)

#Numpy Arrays
N1 = np.arange(size)
N2 = np.arange(size)

start = time.time()

result = [(x,y) for x,y in zip(L1,L2)]

print((time.time() - start))

start = time.time()

result = N1 + N2

print((time.time() - start))


In [0]:
#Size

s=range(1000)
print(sys.getsizeof(1)*len(s))

a=np.arange(1000)
print(a.size*a.itemsize)

**Numpy Basic Operations**

In [0]:
N = np.array([(1,2,3),(4,5,6)])

#Calculate dimensionality of a numpy array
print(N.ndim)

In [0]:
#Calculate byte size of each of the element

print(N.itemsize)

In [0]:
#To Know the datatype stored in array

print(N.dtype)

In [0]:
#Find Total No. of elements in array

print(N.size)

In [0]:
#Find Shape of the array e.g. No. of rows & columns

print(N.shape)

**Reshape and Slicing**

In [0]:
#Reshaping of an array
a= np.array([(1,2,3,4),(2,3,4,5),(3,4,5,6)])

print(a.reshape(6,2))

[[1 2]
 [3 4]
 [2 3]
 [4 5]
 [3 4]
 [5 6]]


In [0]:
#Slicing : It is used for extracting part of a string,or some part of array

print(a[0,1])
print(a[:,0])

2
[1 2 3]


In [0]:
#To get evenly Spaced Samples

a = np.linspace(1,2,5)

print(a)

**Aggregations: Min, Max, and Everything In Between**

In [0]:
N = np.array([1,2,3])

print(N.min())
print(N.max())
print(N.sum())

1
3
6


In [0]:
N = np.array([(1,2,3),(4,5,6)])

print(N.sum(axis=0))
print(N.sum(axis=1))

[5 7 9]
[ 6 15]


In [0]:
#To Calculate Square root of an array
print(np.sqrt(N))

In [0]:
#To Calculate Standard Deviation
print(np.std(N))

In [0]:
#Basic Mathematical Operations

a = np.array([(1,2,3),(4,5,6)])
b = np.array([(1,2,3),(4,5,6)])

print(a + b)
print(a - b)
print(a*b)
print(a/b)

In [0]:
#Stacking
a = np.array([(1,1,1),(2,2,2)])
b = np.array([(3,3,3),(4,4,4)])

print(np.vstack((a,b))) #Vertical Stacking

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


In [0]:
print(np.hstack((a,b))) #Horizontal Stacking

[[1 1 1 3 3 3]
 [2 2 2 4 4 4]]


In [0]:
#Converting a ndarray to 1 D array

print(a.ravel())

[1 1 1 2 2 2]
